# Generated by Django 3.2.19 on 2023-06-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('number', models.CharField(max_length=500)),
                ('size', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=500)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('imageUrl', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Frames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shifr', models.CharField(max_length=500)),
                ('number', models.CharField(max_length=500)),
                ('bold', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=500)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('imageUrl', models.TextField()),
            ],
        ),
    ]
